version: '3.8'

services:
  frontend:
    container_name: tray-vue-ts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
